version: '3'

services:
    web:
      build:
        context: app
        dockerfile: Dockerfile
      environment:
        - NODE_ENV=production
      command: npm start
      ports:
        - 3000:3000
    prisma:
      image: prismagraphql/prisma:1.34
      restart: always
      ports:
        - '127.0.0.1:4466:4466'
      environment:
        PRISMA_CONFIG: |
          port: 4466
          databases:
            default:
              connector: mongo
              uri: mongodb://prisma:prisma@mongo
    mongo:
      image: mongo:3.6
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: prisma
        MONGO_INITDB_ROOT_PASSWORD: prisma
      ports:
        - '127.0.0.1:27018:27018'
      volumes:
        - mongo:/var/lib/mongo

    server:
      build:
        context: .
        dockerfile: Dockerfile
      command: npm start
      ports:
        - '127.0.0.1:4000:4000'
volumes:
  mongo: ~
