version: '3.7'

services:
    web:
      build:
        context: app
        dockerfile: Dockerfile
      environment:
        - NODE_ENV=production
      ports:
        - '127.0.0.1:3000:3000'
      networks:
        - front-back
      volumes:
        - type: bind
          source: ./app
          target: /app
    prisma:
      image: prismagraphql/prisma:1.34
      restart: always
      ports:
        - '127.0.0.1:4466:4466'
      environment:
        PRISMA_CONFIG: |
          port: 4466
          databases:
            default:
              connector: mongo
              uri: mongodb://prisma:prisma@mongo
      networks:
        - back-db
        - back-prisma
    mongo:
      image: mongo:3.6
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: prisma
        MONGO_INITDB_ROOT_PASSWORD: prisma
      ports:
        - '127.0.0.1:27018:27018'
      volumes:
        - mongo:/var/lib/mongo
      networks:
        - back-db

    server:
      build:
        context: server
        dockerfile: Dockerfile
      ports:
        - '127.0.0.1:4000:4000'
      networks:
        - front-back
        - back-prisma
      volumes:
        - type: bind
          source: ./server
          target: /server

networks:
  front-back:
    driver: bridge
  back-prisma:
    driver: bridge
  back-db:
    driver: bridge

volumes:
  mongo: ~
