version: '3'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile.production
    environment:
      - NODE_ENV=production
    command: npm start
    ports:
      - 3000:3000
